### ISSUE TITLE
TS7016: Could not find a declaration file for module 'inline-css' after upgrading to v1.6.0

### ISSUE THREAD

**Issue by squareloop1** [nest-modules/mailer#668]
After upgrading to v1.6.0 from v1.5.1 I get the following error when trying to build the application:

```
node_modules/@nestjs-modules/mailer/dist/interfaces/template-adapter-config.interface.d.ts:1:28 - error TS7016: Could not find a declaration file for module 'inline-css'. '/home/squareloop/test/server/node_modules/inlin
e-css/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/inline-css` if it exists or add a new declaration (.d.ts) file containing `declare module 'inline-css';`

1 import InlineCss = require('inline-css');
```

There are no such issues when building with v1.5.1.

**Comment by xjuanc** [comment]
Were you able to fix this?

**Comment by squareloop1** [comment]
Sadly no. I completely migrated away from this package to [nodemailer](https://www.npmjs.com/package/nodemailer) and [email-templates](https://www.npmjs.com/package/email-templates). I also try to keep my project dependencies clean of any inactive packages nowadays.

**Comment by xjuanc** [comment]
> 

Prob gonna do the same thing. Thanks a lot for such a fast reply!
