### ISSUE TITLE
Breaking change to adapter import paths released as a minor version bump (semver violation)

### ISSUE THREAD

**Issue by olllayor** [nest-modules/mailer#1319]
Between 2.0.2 and 2.3.7, the import path for adapters changed:

2.0.2: @nestjs-modules/mailer/dist/adapters/handlebars.adapter
2.3.7: @nestjs-modules/mailer/adapters/handlebars.adapter

This is a breaking change (existing imports stop resolving, TS2307: Cannot find module) but was shipped under a minor version range, so anyone on a caret/tilde range (^2.0.0, ~2.0.0) — or with lockfile drift across machines/CI — silently breaks on reinstall with no warning.

Repro:

Install 2.0.2, import via dist/adapters/handlebars.adapter → works
Install 2.3.7 with the same import → TS2307
Switch to adapters/handlebars.adapter (no dist) → works on 2.3.7 but breaks on 2.0.2

**Comment by domvanrob** [comment]
Can confirm, this should indeed have been a major bump.
